- id: '1602298536860'
  alias: Tag Vacuum Pause is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 5957db82-93d4-4795-8c8a-4e43dee7aec7
  condition: []
  action:
  - service: vacuum.pause
    data: {}
    entity_id: vacuum.roborock
  mode: single
- id: '1602300036549'
  alias: Tag Bright Front is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: f6f6ebb3-68bf-4405-8596-3c79374af343
  condition: []
  action:
  - service: script.bright_room
    data:
      room: dining_room
  - service: script.bright_room
    data:
      room: living_room
  mode: single
- id: '1602336989035'
  alias: Tag Garage Opener is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 6f9c87a2-fe87-42bb-a224-fe8caba6787e
  condition: []
  action:
  - service: cover.toggle
    data: {}
    entity_id: cover.middle_garage
  mode: single
- id: '1602596187676'
  alias: WFH Bright Front
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: '7:45'
    before: '10:00'
  - condition: or
    conditions:
    - condition: state
      entity_id: group.living_room
      state: 'off'
    - condition: state
      entity_id: group.dining_room
      state: 'off'
  action:
  - service: script.bright_room
    data:
      room: living_room
  - service: script.bright_room
    data:
      room: dining_room
  mode: single
- id: '1603159118621'
  alias: Tag Pool Brushed is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 410b2918-b1ba-4c0d-843b-c2d7aef044fd
  condition: []
  action:
  - service: script.store_pool_brushing
    data: {}
  mode: single
- id: '1603159158058'
  alias: Tag Pool Chemicals Checked is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 0e361d97-c869-474b-9902-1db5fe2abeec
  condition: []
  action:
  - service: script.store_pool_chemicals
    data: {}
  mode: single
- id: '1603159203371'
  alias: Tag Pool Backwashed is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 856a9518-3c9b-4a9c-9bf1-4447b125cc61
  condition: []
  action:
  - service: script.store_pool_backwash
    data: {}
  mode: single
- id: '1603159254708'
  alias: Tag Pool Filter Cleaned is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: 7a36bdf9-8bc7-447f-9162-f881c51ff940
  condition: []
  action:
  - service: script.store_pool_filter_cleaned
    data: {}
  mode: single
- id: '1607052130781'
  alias: Tag Truck Garage Door Opener is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: ff95ee88-68fc-46d7-8e6b-16cfcc2d7083
  condition: []
  action:
  - service: cover.toggle
    data: {}
    entity_id: cover.middle_garage
  mode: single
- id: '1609546605238'
  alias: Hall on with motion sometimes
  description: Hallway lights come on with motion in hall, if nobody in bed and if
    after sunset/before sunrise
  trigger:
  - platform: state
    entity_id: binary_sensor.hallway_motion
    from: 'off'
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.brandie_in_bed
    state: 'off'
  - condition: state
    entity_id: binary_sensor.barrett_in_bed
    state: 'off'
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
    - condition: sun
      after: sunset
  action:
  - service: homeassistant.turn_on
    data: {}
    entity_id: group.hallway
  mode: single
- id: '1618145203714'
  alias: Laundry Room Motion
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.laundry_motion
      no_motion_wait: 300
      light_target:
        entity_id: light.laundry
- id: '1619705307519'
  alias: When the snoo sack is available send brandie and notification
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.snoo_sack_status
    from: Temporarily sold out
  condition: []
  action:
  - service: notify.mobile_app_brandie
    data:
      message: Snoo sack MAY be available
  mode: single
- id: '1621605153327'
  alias: Vacuum Error
  description: ''
  trigger:
  - platform: state
    entity_id: vacuum.roborock
    attribute: state
    to: error
  condition: []
  action:
  - service: notify.mobile_app_brandie
    data:
      title: Vacuum Error
      message: Vacuum has an error. Fix or live in filth.
  mode: single
- id: '1632850897888'
  alias: Tasmota State on Boot
  description: Request state of all tasmota devices on boot
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmotas/state
  mode: single
- id: '1638041536115'
  alias: Bedroom Sensor Broken
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.bedroom_temperature
    to: nan
  condition: []
  action:
  - device_id: ce3c9f645f9b45a99a767a2471908f16
    domain: mobile_app
    type: notify
    message: Bedroom temperature is broken
    title: Alert - Fix Required
  mode: single
- id: '1639888102191'
  alias: Lillian's Temp Sensor Offline
  description: ''
  trigger:
  - device_id: bc541a734916c1b2939155747a40a59e
    domain: zha
    platform: device
    type: device_offline
    subtype: device_offline
  condition:
  - condition: state
    entity_id: switch.hoist_switch
    state: 'on'
  action:
  - service: light.turn_on
    target:
      entity_id: light.barretts_side
    data:
      brightness: 1
  - service: notify.mobile_app_barrett
    data:
      message: Lillian's Sensor is offline and the heater is on!
      title: Warning!
  mode: single
- id: '1641062113818'
  alias: Wake Up
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.barrett_is_charging
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: binary_sensor.brandie_is_charging
    from: 'on'
    to: 'off'
  condition:
  - condition: time
    after: 04:30:00
    before: 09:00:00
  action:
  - service: select.select_option
    target:
      entity_id: select.kitchen_wled_color_palette
    data:
      option: Morning
  mode: single
