- id: '1570973547464'
  alias: Backyard - Coffee Grounds
  trigger:
  - entity_id: binary_sensor.kitchen_door
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunrise
    after_offset: -02:00:00
    before: sunrise
    condition: sun
  action:
  - device_id: 637a9e2d2b8948fca3455942396b7749
    domain: light
    entity_id: light.east_beds
    type: turn_on
  - alias: ''
    data:
      entity_id: switch.globe_lights
    service: homeassistant.turn_on
