- id: '1588709254750'
  alias: New Automation
  description: ''
  trigger:
  - device_id: 976f08d6a2444b11bbf0d34766d2c3b6
    domain: zha
    platform: device
    subtype: button_1
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: light.globe_lights
    service: homeassistant.toggle
