homeassistant:
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/www

system_health:

mobile_app:

recorder:
  exclude:
    domains:
      - updater
    entities:
      - script.flash_kitchen_stop
      - script.flash_kitchen_loop
      - script.flash_driveway_popo
      - script.flash_driveway_loop

  
  
# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

stream:

http:
  base_url: https://***REMOVED***
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1
  login_attempts_threshold: 3
  

websocket_api:

alexa:
  smart_home:
    filter:
      exclude_domains:
        - automation
        - binary_sensor
        - cover
        
shopping_list:

ifttt:
  key: gmYDlPOe-6l8Z4ra6GgplsChRRthv5ixSNJ7V5eVHOJ
  
lovelace:
  mode: storage
  dashboards:
    lovelace-tablet:
      mode: yaml
      filename: tablet-ui.yaml
      title: Family Room Dashboard
      icon: mdi:account-group
      show_in_sidebar: true

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# tuya:
#   username: !secret tuyaUsername
#   password: !secret tuyaPassword
#   country_code: 1

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
      - sun.sun


# View all events in a logbook
logbook:

# influxdb:
#   host: a0d7b954-influxdb
#   port: 8086
#   database: homeassistant
#   username: homeassistant
#   password: !secret influxpass
#   max_retries: 3
#   default_measurement: state
#   exclude:
#     domains:
#       - automation
#       - group
#       - input_boolean
#       - input_datetime
#       - input_number
#       - script
#       - sun
#       - zone

# logger:
#   default: warning
#   logs:
    # homeassistant.components.mqtt: debug
#     homeassistant.components.device_tracker: debug
#     homeassistant.components.aarlo: debug

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

pi_hole:
  host: !secret pihole

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'
  - platform: google_wifi
    host: 192.168.86.1
    scan_interval: 30
  - platform: aarlo
    monitored_conditions:
      - total_cameras
      - battery_level
      - captured_today
      - signal_strength
  - platform: mqtt
    state_topic: "owntracks/Barrett/pixel"
    name: "Barrett Phone Battery"
    unit_of_measurement: "%"
    value_template: '{{ value_json.battery_level }}'
    device_class: battery
  - platform: mqtt
    state_topic: "owntracks/Brandie/pixel"
    name: "Brandie Phone Battery"
    unit_of_measurement: "%"
    value_template: '{{ value_json.battery_level }}'
    device_class: battery
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: memory_use_percent
      - type: ipv4_address
        arg: eth0
      - type: ipv6_address
        arg: eth0
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: last_boot
      - type: load_1m
      - type: load_5m
      - type: processor_use
  - platform: template
    sensors:
      pool_monthly_energy_cost:
        friendly_name: "Monthly Pool Cost"
        value_template: "{{ '%.2f'|format(states('sensor.pool_energy_week')|float * 0.121) }}"
        unit_of_measurement: dollars
        icon_template: mdi:currency-usd
  - platform: template
    sensors:
      ac_monthly_energy_cost:
        friendly_name: "Monthly A/C Cost"
        value_template: "{{ '%.2f'|format(states('sensor.air_conditioner_energy_week')|float * 0.121) }}"
        unit_of_measurement: dollars
        icon_template: mdi:currency-usd



      

speedtestdotnet:
  scan_interval:
    minutes: 25
  monitored_conditions:
    - ping
    - download
    - upload

binary_sensor:
  - platform: template
    sensors:
      trash_day:
        value_template: >
          "{{ now().weekday() == 4 }}"
        friendly_name: "Is Today Trash Day?"
        icon_template: >-
          {% if is_state("binary_sensor.trash_day", "on") %}
          mdi:delete-empty
          {% else %}
          mdi:emoticon-outline
          {% endif %}
      barrett_in_bed:
        value_template: >
          {{ states('binary_sensor.barrett_phone_charging') == 'on' and states('person.barrett') == 'home' }}
      brandie_in_bed:
        value_template: >
          {{ states('binary_sensor.brandie_phone_charging') == 'on' and states('person.brandie') == 'home' }}
  - platform: ffmpeg_noise
    input: !secret nursery_cam_url
    extra_arguments: -filter:a highpass=f=300,lowpass=f=2500,volume=volume=2 -codec:a libmp3lame -ar 16000
    initial_state: false
    duration: 2
    reset: 10
    peak: -20
    name: Nursery Noise

  - platform: aarlo
    monitored_conditions:
      - motion
      - sound
      - ding
  - platform: ping
    name: Internet Connection
    host: 8.8.8.8 #google dns should always be up :)
    scan_interval: 10
  - platform: ping
    name: MQTT Broker
    host: mqtt.***REMOVED***.com
    scan_interval: 60
  # - platform: ping
  #   name: RF Receiver
  #   host: 192.168.86.20
  #   scan_interval: '00:01:00'
  # - platform: mqtt
  #   name: Custom Button
  #   state_topic: "homeassistant/button/1"
  # - platform: mqtt
  #   name: RF Receiver
  #   state_topic: "homeassistant/rfreceiver"
  #   payload_on: 'online'
  #   payload_off: 'offline'
  - platform: mqtt
    state_topic: "owntracks/Barrett/pixel"
    name: "Barrett Phone Charging"
    value_template: "{{ value_json.charging }}"
    payload_on: 'true'
    payload_off: 'false'  
  - platform: mqtt
    state_topic: "owntracks/Brandie/pixel"
    name: "Brandie Phone Charging"
    value_template: "{{ value_json.charging }}"
    payload_on: 'true'
    payload_off: 'false'


# vesync:
#   username: !secret vesync_user
#   password: !secret vesync_password

switch:
  - platform: command_line
    switches:
      pihole_switch:
        command_on: !secret picommand_on
        command_off: !secret picommand_off
        command_state: "curl -X GET 'http://192.168.86.10/admin/api.php?status'"
        value_template: > 
          {{ value_json.status == 'enabled' }}
        friendly_name: Pi Hole Blocking

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

device_tracker:
  - platform: nmap_tracker
    track_new_devices: yes
    hosts: 
      - 192.168.86.0/24
    home_interval: 30
    interval_seconds: 60
  - platform: mqtt_json
    devices:
      barrett_pixel: owntracks/Barrett/pixel
      brandie_pixel: owntracks/Brandie/pixel

fan:
  - platform: mqtt
    name: "Fan Office"
    availability_topic: "homeassistant/tasmota/office_light_and_fan/tele/LWT"
    payload_available: "Online"
    payload_not_available: "Offline"
    state_topic: "homeassistant/tasmota/office_light_and_fan/stat/POWER2"
    command_topic: "homeassistant/tasmota/office_light_and_fan/cmnd/POWER2"
    payload_on: "ON"
    payload_off: "OFF"
    speed_state_topic: "homeassistant/tasmota/office_light_and_fan/stat/FAN_SPEED"
    speed_value_template: "{% if value_json is defined and value_json.Speed is defined %}speed={{ value_json.Speed }}{% endif %}"
    speed_command_topic: "homeassistant/tasmota/office_light_and_fan/cmnd/Event"
    payload_low_speed: "speed=0"
    payload_medium_speed: "speed=1"
    payload_high_speed: "speed=2"
    qos: 1
    speeds:
      - low
      - medium
      - high


person:
#   - name: Barrett
#     id: barrett
#     device_trackers:
#       - device_tracker.barrett_pixel
#       - device_tracker.barrett_pixel_nmap
#   - name: Brandie
#     id: brandie
#     device_trackers:
#       - device_tracker.brandie_pixel
#       - device_tracker.brandie_pixel_nmap


# mqtt:
#   broker: !secret mqtt_broker
#   port: !secret mqtt_port
#   username: homeassistant
#   password: !secret mqtt_password

cover:
  - platform: mqtt
    name: Middle Garage
    command_topic: homeassistant/cover/GarageDoor/set
    state_topic: homeassistant/cover/GarageDoor/state
    availability_topic: homeassistant/cover/GarageDoor
    qos: 0
    retain: false
    payload_open: "Garage1 OPEN"
    payload_close: "Garage1 CLOSE"
    state_open: "Garage1 OPEN"
    state_closed: "Garage1 CLOSED"
    payload_available: "Garages ONLINE"
    payload_not_available: "Garages OFFLINE"
  - platform: mqtt
    name: Near Garage
    command_topic: homeassistant/cover/GarageDoor/set
    state_topic: homeassistant/cover/GarageDoor/state
    availability_topic: homeassistant/cover/GarageDoor
    qos: 0
    retain: false
    payload_open: "Garage3 OPEN"
    payload_close: "Garage3 CLOSE"
    state_open: "Garage3 OPEN"
    state_closed: "Garage3 CLOSED"
    payload_available: "Garages ONLINE"
    payload_not_available: "Garages OFFLINE"
  - platform: mqtt
    name: Far Garage
    command_topic: homeassistant/cover/GarageDoor/set
    state_topic: homeassistant/cover/GarageDoor/state
    availability_topic: homeassistant/cover/GarageDoor
    qos: 0
    retain: false
    payload_open: "Garage2 OPEN"
    payload_close: "Garage2 CLOSE"
    state_open: "Garage2 OPEN"
    state_closed: "Garage2 CLOSED"
    payload_available: "Garages ONLINE"
    payload_not_available: "Garages OFFLINE"
    

neato:
  username: !secret neato_user
  password: !secret neato_password

notify:
  - platform: joaoapps_join
    api_key: !secret join_brandie_api_key
    device_id: !secret join_brandie_device_id
    device_ids: !secret join_brandie_device_id
    name: brandie
  - platform: joaoapps_join
    api_key: !secret join_barrett_api_key
    device_id: !secret join_barrett_device_id
    device_ids: !secret join_barrett_device_id
    name: barrett

joaoapps_join:
  - name: barrett_join
    device_id: group.android
    api_key: !secret join_barrett_api_key
  - name: brandie_join
    device_id: group.android
    api_key: !secret join_brandie_api_key

# xboxone:
spotify:
  client_id: !secret barrett_spotify_client
  client_secret: !secret barrett_spotify_secret

media_player:
  # - platform: snapcast
  #   host: 192.168.86.202
  # - name: Xbox
  #   platform: xboxone
  #   device: FD00EF64AEF7927A
  # - name: Hugh Jass
  #   platform: vizio
  #   host: 192.168.86.211
  #   access_token: Zvejx98jul
  # - name: Local
  #   platform: vlc_telnet
  #   host: localhost
  #   password: mypassword

timer:
  middle_garage:
    duration: '00:05:00'
  near_garage:
    duration: '00:05:00'
  far_garage:
    duration: '00:05:00'
  coffee_timer:
    duration: '00:04:30'

ffmpeg:

aarlo:
  username: !secret arloUser
  password: !secret arloPassword
  refresh_devices_every: 4
  last_format: '%m-%d %H:%M'

# alarm_control_panel:
#   - platform: arlo

camera: 
  - platform: aarlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
  - platform: ffmpeg
    input: rtsp_transport udp -i !secret nursery_cam_url
    name: Nursery Cam
  # - platform: generic
  #   still_image_url: "/config/www/nursery_snapshot.jpg"
  #   stream_source: !secret nursery_cam_url
  #   name: Nursery Camera


#ecobee:
#  api_key: !secret ecobeeAPIKey

weather:
  - platform: nws
    api_key: !secret nws_api_key

zwave:
  usb_path: /dev/ttyUSB0
 
zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db
  
calendar:
#   - platform: todoist
#     token: ea15be5c63c7ee4fe2036e4de72285f53f351af1
  - platform: caldav
    username: barrett
    password: !secret nextcloudPassword
    url: https://nextcloud.***REMOVED***.xyz/remote.php/dav


#google calendar integration
# google:
#   client_id: !secret googleclient_id
#   client_secret: !secret googleclient_secret


shell_command:
  start_neato: "/usr/bin/curl -X GET !secret barrettStartNeatoUrl"
  ring_barrett: "/usr/bin/curl -X GET !secret barrettRingUrl"
  ring_brandie: "/usr/bin/curl -X GET !secret brandieRingUrl"
  curl_post: "curl -X POST -d '{{ data }}' {{ url }}"
  
input_boolean:
  bedroom_diffuser_empty:
    name: Diffuser Empty
    initial: true
    icon: mdi:spray-bottle
  front_door_notify_barrett_home:
    name: Notify Barrett when home
  front_door_notify_barrett_away:
    name: Notify Barrett when away
  christmas_time:
    name: Christmas Time
  entertaining_tonight:
    name: People are coming over tonight
  seed_station_enabled:
    name: Enable the seed station lights
    
input_number:
  globe_light_on_minutes_before_sunset:
    max: 120
    min: 0
  cabinet_nighttime_red:
    max: 255
    min: 0
  cabinet_nighttime_blue:
    max: 255
    min: 0
  cabinet_nighttime_green:
    max: 255
    min: 0    
  cabinet_daytime_red:
    max: 255
    min: 0
  cabinet_daytime_blue:
    max: 255
    min: 0
  cabinet_daytime_green:
    max: 255
    min: 0    
  cabinet_morning_red:
    max: 255
    min: 0
  cabinet_morning_blue:
    max: 255
    min: 0
  cabinet_morning_green:
    max: 255
    min: 0    
    
    
input_datetime:
  outside_lights_off_time:
    has_date: false
    has_time: true
  front_door_notification_start:
    has_date: false
    has_time: true
  front_door_notification_stop:
    has_date: false
    has_time: true
  morning_routine_start_time:
    has_date: false
    has_time: true
  morning_routine_stop_time:
    has_date: false
    has_time: true
  seed_station_on_time:
    has_date: false
    has_time: true
  seed_station_off_time:
    has_date: false
    has_time: true
# input_select:
#   trash_day:
#     name: What day does the trash get picked up
#     options:
#       - Sunday
#       - Monday
#       - Tuesday
#       - Wednesday
#       - Thursday
#       - Friday
#       - Saturday
#     initial: Friday
#     icon: mdi:trash-can

utility_meter:
  pool_energy:
    source: sensor.pool_total_kwh
    cycle: monthly
    offset:
      days: 12
    tariffs:
      - week
      - weekend
  air_conditioner_energy:
    source: sensor.ac_total_kwh
    cycle: monthly
    offset:
      days: 12
    tariffs:
      - week
      - weekend


group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
