- alias: Pool Needs Tending
  trigger:
    platform: time
    at: "11:30:00"
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: "{{ states('sensor.since_pool_last_chem_check') > states('input_number.days_between_pool_chemicals') }}"
      - condition: template
        value_template: "{{  states('sensor.since_pool_last_brushed') > states('input_number.days_between_pool_brushing') }} "
  action:
    - service: notify.everyone
      data_template:
        title: Pool Reminder
        message: >-
          {% if states('sensor.since_pool_last_chem_check') <= states('input_number.days_between_pool_chemicals') %}
            The pool needs to be brushed.
          {% elif states('sensor.since_pool_last_brushed') <= states('input_number.days_between_pool_brushing') %}
            The pool chemicals need to be checked.
          {% else %}
            The pool needs brushing and chemical testing
          {% endif %}
        data:
          clickAction: >-
            {% if states('sensor.since_pool_last_chem_check') > states('input_datetime.pool_chemicals_checked') %}
              https://www.poolmaster.com/wp-content/uploads/2013/03/22260_22264_22270_22280-_5WayTestKitInstructions_English.pdf
            {% else %}
              /lovelace-pool
            {% endif %}
          tag: pool
          sticky: true

- alias: Pool Filter Reminder
  trigger:
    platform: time
    at: "09:30:00"
  condition:
    condition: and
    conditions:
      - condition: or
        conditions:
          - condition: template
            value_template: "{{ states('sensor.since_pool_last_backwashed') >= states('input_number.days_between_pool_backwash') }}"
          - condition: template
            value_template: "{{  states('sensor.since_pool_last_filter_cleaning') >= states('input_number.days_between_pool_filter_cleaning') }} "
      - condition: time
        weekday:
          - sat
  action:
    - service: notify.everyone
      data_template:
        title: Pool Reminder
        message: >-
          {% if states('sensor.since_pool_last_backwashed') < states('input_number.days_between_pool_backwash') %}
            The pool filter needs to be cleaned.
          {% else %}
            The pool filter needs to be backwashed
          {% endif %}
        data:
          clickAction: /lovelace-pool
          tag: pool_filter
          sticky: true