- alias: "Set Theme On Boot"
  trigger:
    platform: homeassistant
    event: start
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
    # - delay:
    #     seconds: 30
    - service: frontend.set_theme
      data:
        name: slate