- alias: New Device Connected
  hide_entity: true
  trigger:
    platform: event
    event_type: device_tracker_new_device
  action:
    - service: notify.barrett
      data_template:
        message: >
          Device Data:
          {{trigger.event.data.host_name}}
          {{trigger.event.data.entity_id}}
        title: New Device
        data:
          icon: https://goo.gl/xeetdy
          
