- alias: Landscape Not Responding
  trigger:
    platform: state
    from: 'home'
    to: 'not_home'
    for: '00:10:00'
    entity_id: device_tracker.front_landscape, device_tracker.back_landscape
  action:
    - service: notify.barrett
      data_template:
        title: "Device Offline"
        message: "{{ trigger.entity_id.split('.')[-1] }} is offline. Please check into it..."