- alias: Outdoor Lights On At Night
  trigger:
  - event: sunset
    platform: sun
    offset: "-00:45:00"
  condition: []
  action:
    - entity_id: group.front_yard
      service: homeassistant.turn_on
    - entity_id: light.front_porch
      service: homeassistant.turn_on
      data:
        brightness: 255
    - data:
        entity_id: light.driveway
        rgb_color:
          - 255
          - 204
          - 114
        brightness: 255
      service: homeassistant.turn_on
    - condition: state
      entity_id: input_boolean.christmas_time
      state: 'on'
    - entity_id: switch.christmas_tree
      service: homeassistant.turn_on

- alias: Nighttime lights off
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (state_attr('input_datetime.outside_lights_off_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  action:
    - service: homeassistant.turn_off
      entity_id: group.front_yard
    - service: homeassistant.turn_off
      entity_id: light.front_porch
    - condition: state
      entity_id: input_boolean.christmas_time
      state: 'on'
    - entity_id: switch.christmas_tree
      service: homeassistant.turn_off