- alias: Entry Light On
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.entry

- alias: Entry Light Off
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'on'
    to: 'off'
    for: 00:05:00
  action:
    service: homeassistant.turn_off
    entity_id: light.entry    