- alias: Entry Light On
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: light.entry
    - delay:
        minutes: 5
    - service: homeassistant.turn_off
      entity_id: light.entry
  mode: restart