- alias: Snapclient Volume on Start
  trigger:
    - platform: state
      entity_id: media_player.snapcast_backyard, media_player.snapcast_kitchen, media_player.snapcast_shop, media_player.snapcast_tv, media_player.snapcast_kitchen
      from: 'off'
      to: 'on'
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: "{{ trigger.entity_id }}"
        volume_level: 0.5


- alias: Snapclient Nightly Reset
  trigger:
    - platform: time
      at: 00:00:00
  action:
    - service: script.reset_all_speakers