- alias: tv_on_with_audio_select
  trigger:
    platform: state
    entity_id: media_player.snapcast_tv
  condition:
    condition: template
    value_template: >
      {{ trigger.to_state.attributes.source != 
      trigger.from_state.attributes.source and
      is_state("media_player.vizio_smartcast","off") }}
  action:
    - service: script.turn_on
      entity_id: script.tv_on_for_music

- alias: tv_on_with_mpd_start
  trigger:
    platform: state
    entity_id: media_player.mpd
    to: playing
  condition:
    condition: template
    value_template: >
      {{  is_state_attr("media_player.snapcast_tv","source","HomeAssistantUI") and 
      is_state("media_player.vizio_smartcast","off") }}
  action:
    - service: script.turn_on
      entity_id: script.tv_on_for_music