- alias: Backyard Morning Off
  trigger:
  - event: sunrise
    platform: sun
  action:
  - entity_id: switch.globe_lights, light.east_beds, light.southeast_corner_bed, light.garden_behind_pool, light.fig_and_sun_deck
    service: homeassistant.turn_off

