alias: Backyard off When Leaving
trigger:
  - entity_id: binary_sensor.house_occupancy
    from: 'on'
    platform: state
    to: 'off'
service: homeassistant.turn_off
data:
  entity_id: group.back_yard