- alias: Backyard On Before Sunset
  trigger:
  - event: sunset
    platform: sun
    offset: "-00:45:00"
  condition:
    condition: state
    entity_id: group.all_people
    state: 'home' #indicates at least 1 person is home
  action:
    service: homeassistant.turn_on
    entity_id: group.back_yard