- alias: Backyard On Before Sunset
  trigger:
  - event: sunset
    platform: sun
    offset: "-00:45:00"
  condition:
    condition: state
    entity_id: binary_sensor.house_occupancy
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.back_yard