- alias: Backyard on when Coming Home
  trigger: 
    platform: state
    entity_id: binary_sensor.house_occupancy
    to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:45:00"
  action:
    service: homeassistant.turn_on
    entity_id:
      - group.back_yard