- alias: Aurora
  id: 'AURORA'
  action:
    - service: notify.mobile_app_barrett
      data:
        message: 'There is a chance to see the northern lights in the next 5 minutes!'
        title: Northern Lights
        data:
          icon: https://goo.gl/xeetdy
    - service: notify.mobile_app_brandie
      data:
        message: 'There is a chance to see the northern lights in the next 5 minutes!'
        title: Northern Lights
        data:
          icon: https://goo.gl/xeetdy
  trigger:
    - platform: state
      entity_id: binary_sensor.northernlights_sensor
      from: 'off'
      to: 'on'



- alias: Coffee Timer Expired
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.coffee_timer
  action:
    - service: script.turn_on
      entity_id: script.flash_kitchen



- alias: Test Notify
  action:
    - service: notify.mobile_app_brandie
      data:
        message: Test Notification
        title: TEST
        data:
          icon: https://goo.gl/xeetdy
    - service: notify.mobile_app_barrett
      data:
        message: Test Notification
        title: TEST
        data:
          icon: https://goo.gl/xeetdy
  condition: []
  id: '1524716348156'
  trigger: []

- id: 'BELLEAVES'
  alias: Barrett Leaves
  trigger:
  - entity_id: person.barrett
    from: 'home'
    platform: state
    to: 'not_home'
  condition:
  - condition: state
    entity_id: group.brandie
    state: 'not_home'
  - condition: state
    entity_id: cover.middle_garage
    state: 'open'
  action:
  - data:
      message: The middle garage is open but nobody is home!
      title: Garage Alert
    service: notify.mobile_app_barrett

- id: 'BLLLEAVES'
  alias: Brandie Leaves
  trigger:
  - entity_id: person.brandie
    from: 'home'
    platform: state
    to: 'not_home'
  condition:
  - condition: state
    entity_id: group.barrett
    state: 'not_home'
  - condition: state
    entity_id: cover.middle_garage
    state: 'open'
  action:
  - data:
      message: The middle garage is open but nobody is home!
      title: Garage Alert
    service: notify.mobile_app_brandie


- alias: Notify Brandie when Barrett's Phone is about to die
  trigger:
    platform: numeric_state
    entity_id: device_tracker.barrett_pixel
    value_template: '{{ states("sensor.barrett_phone_battery") }}'
    below: 20
  action:
    - service: notify.mobile_app_brandie
      data:
        message: FYI - Barrett's phone battery < 20%
        title: Barrett's Phone is Dying
        
- alias: Notify Barrett when Brandie's Phone is about to die
  trigger:
    platform: numeric_state
    entity_id: device_tracker.brandie_pixel
    value_template: '{{ states("sensor.brandie_phone_battery") }}'
    below: 20
  action:
    - service: notify.mobile_app_barrett
      data:
        message: FYI - Brandie's phone battery < 20%
        title: Brandie's Phone is Dying


- alias: Log Backwash
  trigger:
    entity_id: binary_sensor.custom_button
    from: 'off'
    to: 'on'
    platform: state
  action:
    service: homeassistant.toggle
    entity_id: group.kitchen
    # - service: ifttt.trigger
    #   data:
    #     event: "pool_log_backwash"
    #     value1: "Backwash"
    #     value2: "Home Assistant"

        

# - id: 'Coffee Timer'
#   alias: Coffee Timer
#   trigger:
#     entity_id: binary_sensor.custom_button
#     from: 'off'
#     to: 'on'
#     platform: state
#   action:
#     - service_template: >
#         {% if is_state('script.flash_kitchen', 'on') or is_state('script.flash_kitchen_loop', 'on') %}
#         script.turn_off
#         {% else %}
#         timer.start
#         {% endif %}
#       data_template:
#         entity_id: >-
#           {% if is_state('script.flash_kitchen', 'on') or is_state('script.flash_kitchen_loop', 'on') %} 
#           script.flash_kitchen, script.flash_kitchen_loop
#           {% else %}
#           timer.coffee_timer
#           {% endif %}
#     - service: light.turn_off
#       entity_id: light.brandies_desk
#     - delay: '00:00:01'
#     - service: light.turn_on
#       entity_id: light.brandies_desk