# This automation turs on the bedroom lights in the evening when someone enters the hallway
- alias: Bedroom on in morning
  condition:
    condition: and
    conditions:
    # do not trigger if Barrett isn't home
      - condition: state
        entity_id: binary_sensor.barrett_in_bed
        state: 'off'
      - condition: state
        entity_id: binary_sensor.brandie_in_bed
        state: 'off'
      - condition: time
        before: "10:00:00"
      #and someone is home
      - condition: state
        entity_id: binary_sensor.house_occupancy
        state: 'on'
      - condition: state
        entity_id: input_select.vacation_mode
        state: 'Home'
      - condition: state
        entity_id: group.bedroom
        state: 'off'
  trigger: 
    platform: state
    entity_id: binary_sensor.hallway_motion
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.bedroom
    data:
      brightness: 255
