- alias: Notify if Garage Opened
  trigger:
    - platform: state
      entity_id: cover.middle_garage
      to: 'open'
      for: 00:05:00
    - platform: state
      entity_id: cover.near_garage
      to: 'open'
      for: 00:05:00
    - platform: state
      entity_id: cover.far_garage
      to: 'open'
      for: 00:05:00
  action:
    - service: notify.barrett
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }} has been opened for 5 minutes
        title: 'Alert'

