- alias: Pantry Auto On
  action:
    - data:
        entity_id: light.pantry
      service: light.turn_on
    - data:
        entity_id: light.pantry
        # transition: 1
        #brightness: 254
      service: light.turn_on
  # condition:
  #   condition: template
  #   value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  trigger:
    entity_id: binary_sensor.pantry_door
    platform: state
    to: "on"
- alias: Pantry Auto Off
  action:
    service: light.turn_off
    entity_id: light.pantry
  # condition:
  #   condition: template
  #   value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  trigger:
    entity_id: binary_sensor.pantry_door
    platform: state
    to: "off"
