- alias: Pantry Auto On and Off
  action:
    - data:
        entity_id: light.pantry
        transition: 1
        brightness: 255
      service_template: >
        {% if trigger.to_state.state == 'off' and trigger.from_state.state == 'on' %}
        light.toggle
        {% else %}
        light.turn_on
        {% endif %}
  condition:
    condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  trigger:
    entity_id: binary_sensor.pantry_door
    platform: state