- alias: Sliding Door Left Open
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_door
      to: open
      for: "00:01:30"
    - platform: numeric_state
      entity_id: sensor.air_conditioner_power
      above: 30
  condition:
    condition: and
    conditions:
      - condition: numeric_state
        entity_id: sensor.air_conditioner_power
        above: 30 #arbitrary number of watts that seems good... :)
      - condition: template
        value_template: "{{ (state_attr('weather.kfws_daynight', 'temperature')|int) > 78 }}"
  action:
    - service: notify.alexa_media
      data:
        target: 
          - media_player.kitchen
          - media_player.bedroom
        message: "It's kind of warm out. Want to close the kitchen door?"
        data:
          type: tts
    - service: notify.everyone
      data:
        title: ALERT
        message: "We're cooling Texas. Close the doors!"
        data:
          tag: sliding_door
          sticky: true
    - service: automation.turn_on
      entity_id: automation.sliding_door_notification_cancel

- alias: Sliding Door Notification Cancel
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_door
      to: closed
  action:
    - service: notify.everyone
      data:
        message: clear_notification
        data:
          tag: sliding_door
    - service: automation.turn_off
      entity_id: automation.sliding_door_notification_start