- alias: Evening Lighting
  trigger: 
    platform: time
    at: "21:00:00"
  condition:
    - condition: state
      entity_id: binary_sensor.house_occupancy
      state: 'on'
  action:
    - service: python_script.reduce_all_lights_by_pct
      data:
        transition: 30
        color_temp: 440 # Amber Tone
        pct: 50