- alias: Late Afternoon
  trigger:
  - event: sunset
    platform: sun
    offset: "-00:45:00"
  condition:
    condition: and
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: input_select.vacation_mode
            state:  'Away'
      - condition: state
        entity_id: binary_sensor.house_occupancy
        state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.family_room
        transition: 60
        color_temp: 375
        brightness: 255
    - service: switch.turn_on
      entity_id: group.family_room
    - service: light.turn_on 
      data:
        entity_id: group.bedroom
        brightness: 255
        transition: 30
    - service: switch.turn_on
      entity_id: group.bedroom