- alias: Late Afternoon
  trigger:
  - event: sunset
    platform: sun
    offset: "-01:05:00"
  condition:
    - condition: state
      entity_id: binary_sensor.house_occupancy
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: group.family_room, group.living_room
        transition: 60
        color_temp: 375
        brightness: 255
    - service: light.turn_on 
      data:
        entity_id: group.bedroom
        brightness: 255
        transition: 30
    - service: switch.turn_on
      entity_id: group.bedroom