- alias: Late Afternoon
  trigger:
  - event: sunset
    platform: sun
    offset: "-01:00:00"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: person.barrett
          state: home
        - condition: state
          entity_id: person.brandie
          state: home
  action:
    - service: light.turn_on
      data:
        entity_id: group.family_room
        transition: 60
        color_temp: 375
        brightness: 255
    - service: light.turn_on 
      data:
        entity_id: group.bedroom
        brightness: 255
        transition: 30