- alias: Plex Dim On Play
  trigger:
    - platform: state
      entity_id: media_player.plex_plex_for_xbox_xboxone
      to: 'playing'
  condition:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"
  action:
    - service: scene.create
      data:
        scene_id: pre_plex_scene
        snapshot_entities:
          - light.recessed_lights
          - light.fireplace_lamp
          - switch.kitchen_crappy
          - light.bar
    - event: MANUAL_DIM
      event_data:
        entity_id: light.recessed_lights
        brightness: "{{ state_attr('light.recessed_lights', 'brightness') / 2 }}"
        transition: 2
    - service: light.turn_on
      data_template:
        entity_id: light.bar
        brightness: "{{ state_attr('light.bar', 'brightness') / 2 }}"
        transition: 2
    - service: light.turn_on
      data_template:
        entity_id: light.kitchen_desk
        brightness: "{{ state_attr('light.kitchen_desk', 'brightness') / 2 }}"
        transition: 2
    - service: light.turn_off
      data:
        transition: 2
        entity_id: 
          - light.fireplace_lamp
          - light.hallway_north
          - light.hallway_south
    - service: switch.turn_off
      entity_id: switch.kitchen_crappy
    - service: homeassistant.turn_off
      entity_id: automation.plex_dim_on_play

- alias: Plex Brighten When Paused
  trigger:
    - platform: state
      entity_id: media_player.plex_plex_for_xbox_xboxone
      from: 'playing'
      to: 'paused'
      for:
        seconds: 30
    - platform: state
      entity_id: media_player.plex_plex_for_xbox_xboxone
      to: 'idle'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.pre_plex_scene
    - service: homeassistant.turn_on
      entity_id: automation.plex_dim_on_play
  