- alias: Start The Day
  trigger:
    platform: state
    entity_id: binary_sensor.hallway_motion
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.interior
        state: 'off'
      - condition: template
        value_template: "{{ states('sensor.time') >= (state_attr('input_datetime.morning_routine_start_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
      - condition: template
        value_template: "{{ states('sensor.time') < (state_attr('input_datetime.morning_routine_stop_time', 'timestamp') | int | timestamp_custom('%H:%M', False)) }}"
  action:
    - service: homeassistant.turn_on
      data:
        entity_id:
          - light.sink
          - light.kitchen_lamp
          - light.smells_shelf
          - light.bar
          - light.under_cabinet_lights
          - light.mantle_lamp
        transition: 120
    - delay: '00:02:00'
    - service: homeassistant.turn_on
      data:
        entity_id:
          - switch.mantle
          - light.kitchen_desk