- alias: Trash Reminder the Night Before
  trigger:
    platform: time
    at: '18:00:00'
  condition:
    conditions:
      - condition: template
        alias: "State contains 'Tomorrow'"
        value_template: >
          {{ 'Tomorrow' in states('sensor.trash_day') }}
  action: 
    service:
      - notify.mobile_app_barrett
      - notify.mobile_app_brandie
    data:
      message: The trash needs to be taken out tonight, don't forget!
      title: Don't let it stink!
      
- alias: Trash Reminder the Morning Of
  trigger:
    platform: state
    entity_id:
      - binary_sensor.barrett_is_charging
      - binary_sensor.brandie_is_charging
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: template
        alias: "State contains 'Today'"
        value_template: >
          {{ 'Today' in states('sensor.trash_day') }}
      - condition: time
        after: '05:00:00'
        before: '11:00:00'
  action:
    service_template: >-
      notify.{{ (trigger.entity_id.split('.')[-1]).split('_')[0] }}
    data:
      message: "Today is trash day. Don't forget!"
      title: "Good Morning!"
      
      
      