# Start vacuum during the week
- alias: Vacuum Family Room and Kitchen
  action:
    - service: python_script.vacuum_zones
      data:
        zones:
          - "Family Room"
          - "Kitchen"
  trigger:
    platform: time
    at: '08:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - wed
    - fri

- alias: Vacuum Bedroom and Hallway
  action:
    - service: python_script.vacuum_zones
      data:
        zones:
          - "Bedroom"
          - "Hall"

  trigger:
    platform: time
    at: '08:00:00'
  condition:
  - condition: time
    weekday:
    - tue

- alias: Vacuum Living and Dining Rooms
  action:
    - service: python_script.vacuum_zones
      data:
        zones:
          - "Living Room"
          - "Dining Room"
  trigger:
    platform: time
    at: '08:00:00'
  condition:
  - condition: time
    weekday:
    - thu

- alias: Vacuum Office and Guest Bath
  action:
    - service: python_script.vacuum_zones
      data:
        zones:
          - "Office"
          - "Guest Bath"
  trigger:
    platform: time
    at: '12:00:00'
  condition:
  - condition: time
    weekday:
    - wed

- alias: Vacuum To Trashcan
  # initial_state: false
  action:
    - delay: '00:00:02'
    - service: vacuum.pause
      entity_id: vacuum.roborock
    - delay: '00:00:02'
    - service: vacuum.send_command
      data:
        entity_id: vacuum.roborock
        command: 'go_to'
        params:
          'spot_id': 'Trashcan'
    - service: automation.turn_off
      entity_id: automation.vacuum_to_trashcan
  trigger:
    - platform: state
      entity_id: vacuum.roborock
      to: returning

- alias: Vacuum Started Notifications
  trigger:
    - platform: state
      entity_id: vacuum.roborock
      from: docked
  action:
    - service: notify.everyone
      data:
        title: Vacuum Running
        message: 'Tap "view" to access it'
        data:
          actions:
            - action: URI
              title: View
              uri: '/lovelace/vacuum'
          tag: vacuum
          sticky: true

- alias: Vacuum Ended Notifications
  trigger:
    - platform: state
      entity_id: vacuum.roborock
      to: docked
  action:
    - service: notify.everyone
      data:
        message: clear_notification
        data:
          tag: vacuum
