- alias: Nursery Button 1 Hold
  description: ''
  trigger:
  - device_id: 7b61b4e7a5a143aba0f231ebec9c2d3e
    domain: zha
    platform: device
    subtype: button_1
    type: remote_button_long_press
  condition: []
  action:
  - data: {}
    service: script.nursery_button_1_hold
- alias: Nursery Button 2 Hold
  description: ''
  trigger:
  - device_id: 7b61b4e7a5a143aba0f231ebec9c2d3e
    domain: zha
    platform: device
    subtype: button_2
    type: remote_button_long_press
  condition: []
  action:
  - data: {}
    service: script.nursery_button_2_hold

- alias: Nursery Button 3 Hold
  description: ''
  trigger:
  - device_id: 7b61b4e7a5a143aba0f231ebec9c2d3e
    domain: zha
    platform: device
    subtype: button_3
    type: remote_button_long_press
  condition: []
  action:
  - data: {}
    service: script.nursery_button_3_hold

- alias: Nursery Button 4 Hold
  description: ''
  trigger:
  - device_id: 7b61b4e7a5a143aba0f231ebec9c2d3e
    domain: zha
    platform: device
    subtype: button_4
    type: remote_button_long_press
  condition: []
  action:
  - data: {}
    service: script.nursery_button_4_hold


- alias: Nursery Button 1 Press
  description: ''
  trigger:
  - device_id: 7b61b4e7a5a143aba0f231ebec9c2d3e
    domain: zha
    platform: device
    subtype: button_1
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: light.recessed_lights
    service: script.nursery_button_1_press
- alias: Nursery Button 2 Press
  description: ''
  trigger:
  - device_id: 7b61b4e7a5a143aba0f231ebec9c2d3e
    domain: zha
    platform: device
    subtype: button_2
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: light.mantle_lamp
    service: script.nursery_button_2_press
- alias: Nursery Button 3 Press
  description: ''
  trigger:
  - device_id: 7b61b4e7a5a143aba0f231ebec9c2d3e
    domain: zha
    platform: device
    subtype: button_3
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: script.nursery_button_3_press
    service: script.nursery_button_3_press
- alias: Nursery Button 4 Press
  description: ''
  trigger:
  - device_id: 7b61b4e7a5a143aba0f231ebec9c2d3e
    domain: zha
    platform: device
    subtype: button_4
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    service: script.nursery_button_4_press