- alias: Nursery Noise Notification
  trigger:   
    - platform: state
      entity_id: binary_sensor.nursery_noise
      from:  'off'
      to:  'on'
  action:
    - service: python_script.notify_via_light
      data:
        entity_id: light.barretts_side
    - service: light.turn_on
      entity_id: light.dresser

- alias: Nursery Noise Notify Barrett
  trigger:
    - platform: state
      entity_id: binary_sensor.nursery_noise
      from:  'off'
      to:  'on'
  action:
    - service: notify.mobile_app_barrett
      data:
        title: Hey, Dad!
        message: Lillian may be awake.