- alias: Sconces Off When In Crib
  trigger:   
    - platform: state
      entity_id: binary_sensor.crib_occupied
      from:  'off'
      to:  'on'
  condition:
    - condition: state
      entity_id: light.nursery_sconces
      state:  'on'
  action:
    - service: light.turn_off
      entity_id: light.nursery_sconces